In [38]:
import torch

In [39]:
frame_batch = torch.tensor([1, 1, 1, 1, 2, 2, 2, 2])
mol_batch = torch.tensor([1, 1, 2, 2, 3, 3, 4, 4])
sites = torch.rand(frame_batch.size(0), 3)
print(frame_batch)
print(mol_batch)
print(sites)

tensor([1, 1, 1, 1, 2, 2, 2, 2])
tensor([1, 1, 2, 2, 3, 3, 4, 4])
tensor([[0.3563, 0.6403, 0.9999],
        [0.3647, 0.3279, 0.3415],
        [0.2687, 0.8052, 0.8887],
        [0.5398, 0.9870, 0.7265],
        [0.0278, 0.0429, 0.7752],
        [0.3030, 0.4340, 0.4359],
        [0.0296, 0.4386, 0.1591],
        [0.2475, 0.5485, 0.4218]])


In [40]:
same_frame = frame_batch.unsqueeze(0) == frame_batch.unsqueeze(1)
different_mol = mol_batch.unsqueeze(0) != mol_batch.unsqueeze(1)
print(same_frame)
print(different_mol)

tensor([[ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True]])
tensor([[False, False,  True,  True,  True,  True,  True,  True],
        [False, False,  True,  True,  True,  True,  True,  True],
        [ True,  True, False, False,  True,  True,  True,  True],
        [ True,  True, False, False,  True,  True,  True,  True],
        [ True,  True,  True,  True, False, False,  True,  True],
        [ True,  True,  True,  True, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True, False, False],
        [

In [41]:
valid_pairs = same_frame & different_mol
print(valid_pairs)

tensor([[False, False,  True,  True, False, False, False, False],
        [False, False,  True,  True, False, False, False, False],
        [ True,  True, False, False, False, False, False, False],
        [ True,  True, False, False, False, False, False, False],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False,  True,  True],
        [False, False, False, False,  True,  True, False, False],
        [False, False, False, False,  True,  True, False, False]])


In [42]:
indices = torch.nonzero(valid_pairs)
print(indices.shape)
print(indices)

torch.Size([16, 2])
tensor([[0, 2],
        [0, 3],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [4, 6],
        [4, 7],
        [5, 6],
        [5, 7],
        [6, 4],
        [6, 5],
        [7, 4],
        [7, 5]])


In [43]:
print(sites[indices].shape)
print(sites[indices])

torch.Size([16, 2, 3])
tensor([[[0.3563, 0.6403, 0.9999],
         [0.2687, 0.8052, 0.8887]],

        [[0.3563, 0.6403, 0.9999],
         [0.5398, 0.9870, 0.7265]],

        [[0.3647, 0.3279, 0.3415],
         [0.2687, 0.8052, 0.8887]],

        [[0.3647, 0.3279, 0.3415],
         [0.5398, 0.9870, 0.7265]],

        [[0.2687, 0.8052, 0.8887],
         [0.3563, 0.6403, 0.9999]],

        [[0.2687, 0.8052, 0.8887],
         [0.3647, 0.3279, 0.3415]],

        [[0.5398, 0.9870, 0.7265],
         [0.3563, 0.6403, 0.9999]],

        [[0.5398, 0.9870, 0.7265],
         [0.3647, 0.3279, 0.3415]],

        [[0.0278, 0.0429, 0.7752],
         [0.0296, 0.4386, 0.1591]],

        [[0.0278, 0.0429, 0.7752],
         [0.2475, 0.5485, 0.4218]],

        [[0.3030, 0.4340, 0.4359],
         [0.0296, 0.4386, 0.1591]],

        [[0.3030, 0.4340, 0.4359],
         [0.2475, 0.5485, 0.4218]],

        [[0.0296, 0.4386, 0.1591],
         [0.0278, 0.0429, 0.7752]],

        [[0.0296, 0.4386, 0.1591],
      

In [48]:
site_pairs = sites[indices]
print(site_pairs[:, 0])
print(site_pairs[:, 0, :])
print(site_pairs[:, 1] == site_pairs[:, 1, :])

tensor([[0.3563, 0.6403, 0.9999],
        [0.3563, 0.6403, 0.9999],
        [0.3647, 0.3279, 0.3415],
        [0.3647, 0.3279, 0.3415],
        [0.2687, 0.8052, 0.8887],
        [0.2687, 0.8052, 0.8887],
        [0.5398, 0.9870, 0.7265],
        [0.5398, 0.9870, 0.7265],
        [0.0278, 0.0429, 0.7752],
        [0.0278, 0.0429, 0.7752],
        [0.3030, 0.4340, 0.4359],
        [0.3030, 0.4340, 0.4359],
        [0.0296, 0.4386, 0.1591],
        [0.0296, 0.4386, 0.1591],
        [0.2475, 0.5485, 0.4218],
        [0.2475, 0.5485, 0.4218]])
tensor([[0.3563, 0.6403, 0.9999],
        [0.3563, 0.6403, 0.9999],
        [0.3647, 0.3279, 0.3415],
        [0.3647, 0.3279, 0.3415],
        [0.2687, 0.8052, 0.8887],
        [0.2687, 0.8052, 0.8887],
        [0.5398, 0.9870, 0.7265],
        [0.5398, 0.9870, 0.7265],
        [0.0278, 0.0429, 0.7752],
        [0.0278, 0.0429, 0.7752],
        [0.3030, 0.4340, 0.4359],
        [0.3030, 0.4340, 0.4359],
        [0.0296, 0.4386, 0.1591],
        [0.02

In [51]:
distances = torch.norm(site_pairs[:, 0] - site_pairs[:, 1], dim=-1)
print(distances.shape)
print(distances)

torch.Size([16])
tensor([0.2174, 0.4782, 0.7324, 0.7832, 0.2174, 0.7324, 0.4782, 0.7832, 0.7322,
        0.6549, 0.3891, 0.1281, 0.7322, 0.3891, 0.6549, 0.1281])
