In [2]:
import torch

In [3]:
atom_batch = torch.tensor([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])
atoms_per_mol = 3
atom_batch = atom_batch.view(-1, atoms_per_mol)
print(atom_batch)

tensor([[0, 0, 0],
        [0, 0, 0],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [5]:
mol_batch = atom_batch[:, 0]
print(mol_batch)

tensor([0, 0, 1, 1, 1])


In [7]:
num_sites = 4
sites_batch = mol_batch.repeat_interleave(num_sites)
print(sites_batch)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [8]:
site_params = torch.randn(num_sites, 2)
print(site_params)

tensor([[ 0.2161,  0.1315],
        [ 0.9323, -0.5339],
        [-1.1132,  1.1016],
        [-2.2855, -1.4280]])


In [14]:
num_mols = 2
site_params.repeat(num_mols, 1)

tensor([[ 0.2161,  0.1315],
        [ 0.9323, -0.5339],
        [-1.1132,  1.1016],
        [-2.2855, -1.4280],
        [ 0.2161,  0.1315],
        [ 0.9323, -0.5339],
        [-1.1132,  1.1016],
        [-2.2855, -1.4280]])