In [9]:
import numpy as np
import torch
from ase import Atoms
from matscipy.neighbours import neighbour_list

In [4]:
pos = np.array([[0, 0, 0], [3, 3, 3]])
cell = [3.5, 3.5, 3.5]
pbcs = [True, True, True]
atoms = Atoms(positions=pos, cell=cell, pbc=pbcs)

In [6]:
i, j, d, D, S = neighbour_list("ijdDS", atoms, cutoff=1.0)

In [8]:
print(i)
print(j)
print(d)
print(D)
print(S)

[0 1]
[1 0]
[0.8660254 0.8660254]
[[-0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5]]
[[-1 -1 -1]
 [ 1  1  1]]


In [10]:
torch.tensor([i, j])

/tmp/ipykernel_115793/3223926993.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:274.)
  torch.tensor([i,j])


tensor([[0, 1],
        [1, 0]], dtype=torch.int32)