In [14]:
import torch

In [15]:
num_molecules = 2
num_basis = 3
num_dimensions = 3
x = torch.randint(10, (num_molecules, num_basis, num_dimensions))
print(x)
print(x.shape)

tensor([[[6, 5, 8],
         [0, 8, 9],
         [3, 3, 3]],

        [[4, 7, 3],
         [7, 2, 2],
         [6, 3, 3]]])
torch.Size([2, 3, 3])


In [16]:
num_sites = 4
weights = torch.randint(10, (num_sites, num_basis))
print(weights)
print(weights.shape)

tensor([[4, 8, 5],
        [8, 8, 9],
        [1, 5, 3],
        [1, 9, 1]])
torch.Size([4, 3])


In [17]:
print(weights.unsqueeze(0).expand(num_molecules, -1, -1))
print(weights.unsqueeze(0).expand(num_molecules, -1, -1).shape)

tensor([[[4, 8, 5],
         [8, 8, 9],
         [1, 5, 3],
         [1, 9, 1]],

        [[4, 8, 5],
         [8, 8, 9],
         [1, 5, 3],
         [1, 9, 1]]])
torch.Size([2, 4, 3])


In [18]:
torch.bmm(weights.unsqueeze(0).expand(num_molecules, -1, -1), x)

tensor([[[ 39,  99, 119],
         [ 75, 131, 163],
         [ 15,  54,  62],
         [  9,  80,  92]],

        [[102,  59,  43],
         [142,  99,  67],
         [ 57,  26,  22],
         [ 73,  28,  24]]])