In [34]:
import torch

In [35]:
num_molecules = 2
num_atoms = 3
num_dimensions = 3
x = torch.randint(10, (num_molecules * num_atoms * num_dimensions,))
print(x)

tensor([5, 0, 1, 2, 2, 4, 3, 5, 4, 7, 3, 8, 7, 9, 3, 8, 1, 9])


In [36]:
x = x.reshape(num_molecules, num_atoms, num_dimensions)
print(x)

tensor([[[5, 0, 1],
         [2, 2, 4],
         [3, 5, 4]],

        [[7, 3, 8],
         [7, 9, 3],
         [8, 1, 9]]])


In [37]:
r_O1 = x[0, 0]
print(r_O1)

tensor([5, 0, 1])


In [38]:
x - r_O1

tensor([[[ 0,  0,  0],
         [-3,  2,  3],
         [-2,  5,  3]],

        [[ 2,  3,  7],
         [ 2,  9,  2],
         [ 3,  1,  8]]])

In [39]:
r_O = x[:, 0, :]
print(r_O)
print(r_O.shape)

tensor([[5, 0, 1],
        [7, 3, 8]])
torch.Size([2, 3])


In [40]:
r_O_broadcasted = r_O[:, None, :]
print(r_O_broadcasted)
print(r_O_broadcasted.shape)

tensor([[[5, 0, 1]],

        [[7, 3, 8]]])
torch.Size([2, 1, 3])


In [41]:
y = x - r_O_broadcasted
print(y)
print(y.shape)

tensor([[[ 0,  0,  0],
         [-3,  2,  3],
         [-2,  5,  3]],

        [[ 0,  0,  0],
         [ 0,  6, -5],
         [ 1, -2,  1]]])
torch.Size([2, 3, 3])


In [42]:
cross_products = torch.linalg.cross(y[:, 1, :], y[:, 2, :])
print(y[:, 1, :])
print(y[:, 2, :])
print(cross_products)
print(cross_products.shape)

tensor([[-3,  2,  3],
        [ 0,  6, -5]])
tensor([[-2,  5,  3],
        [ 1, -2,  1]])
tensor([[ -9,   3, -11],
        [ -4,  -5,  -6]])
torch.Size([2, 3])


In [45]:
y[:, 0, :] = cross_products
print(y)
print(y.shape)

tensor([[[ -9,   3, -11],
         [ -3,   2,   3],
         [ -2,   5,   3]],

        [[ -4,  -5,  -6],
         [  0,   6,  -5],
         [  1,  -2,   1]]])
torch.Size([2, 3, 3])
